### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [SayHelloGmbH/hello-roots#10]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/SayHelloGmbH/hello-roots/blob/master/package.json#L16

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by nico-martin** [comment]
Hi @DanielRuf,

Yes, you're right. I removed it from the package.json and it still works without the fs-package.
Thanks for pointing that out!
